name:         megaparsec-utils
version:      0.0.0.0-dev
license:      GPL-3
author:       drlkf
maintainer:   drlkf@drlkf.net
copyright:    2024 drlkf
license-file: LICENSE
github:       drlkf/megaparsec-utils
homepage:     https://github.com/drlkf/megaparsec-utils
bug-reports:  https://github.com/drlkf/megaparsec-utils/issues
category:     Parsing

extra-source-files:
  - README.md
  - CHANGELOG.md

synopsis: Parsers and utilities for the Megaparsec library.
description: |
  Common parsers and utilities to use with the Megaparsec library.

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 2.0 && < 3
  - megaparsec >= 9.0 && < 10
  - parser-combinators >= 1.0 && < 2
  - text >= 2.0 && < 3
  - time >= 1.10 && < 2
  - uuid >= 1.3 && < 2

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

tests:
  megaparsec-utils-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - megaparsec-utils
      - hspec
      - QuickCheck
