---
name: Semantic release
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Semantic release
    environment: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Semantic release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          HACKAGE_KEY: ${{ secrets.HACKAGE_TOKEN }}

        with:
          ci: ${{ github.ref == 'refs/heads/main' }}
          extra_plugins: |
            conventional-changelog-conventionalcommits
            semantic-release-mirror-version
            semantic-release-stack-upload

      - name: Semantic release output
        run: |
          echo ref: ${{ github.ref }}
          echo dry_run: ${{ github.ref != 'refs/heads/main' }}
          echo published: ${{ steps.semantic.outputs.new_release_published }}
          echo last_release: ${{ steps.semantic.outputs.last_release_version }}
          echo new_version: ${{ steps.semantic.outputs.new_release_version }}
          echo git_head: ${{ steps.semantic.outputs.new_release_git_head }}

          echo release_notes:
          echo "${{ steps.semantic.outputs.new_release_notes }}"
...
