---
name: Semantic release
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Semantic release
    environment: master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Semantic release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          HACKAGE_TOKEN: ${{ secrets.HACKAGE_TOKEN }}

        with:
          ci: ${{ env.GITHUB_REF == 'refs/head/master' }}
          extra_plugins: |
            semantic-release-mirror-version
            semantic-release-hackage

      - name: Semantic release output
        run: |
          echo dry_run: ${{ env.GITHUB_REF != 'refs/head/master' }}
          echo published: ${{ steps.semantic.outputs.new_release_published }}
          echo last_release: ${{ steps.semantic.outputs.last_release_version }}
          echo new_version: ${{ steps.semantic.outputs.new_release_version }}
          echo git_head: ${{ steps.semantic.outputs.new_release_git_head }}

          echo release_notes:
          echo "${{ steps.semantic.outputs.new_release_notes }}"
...
